### PR TITLE
Fix wnyc mobile streampad

### PR DESCRIPTION
**Pull request by marineb**
The mobile streampad isn't loading on WNYC. Made the class name for our new streampad specific to WQXR until we launch this version on WNYC.

### CODE REVIEW

**Comment by noslouch** [comment]
:-1: I don't like this. These libraries shouldn't have any property specific naming in their classes.

**Comment by marineb** [comment]
@noslouch I meant this as something temporary until we release the new streambanner on wnyc.

**Comment by noslouch** [comment]
what do you think about #28? it should achieve the same result using a permanent fix instead of a temporary wqxr prefix?

**Comment by marineb** [comment]
@noslouch totally! I should have thought about doing that instead!

**Comment by noslouch** [comment]
great. I'll revert that PR and merge this in if that's OK with you?

**Comment by marineb** [comment]
Sounds good! You know I had already rebuilt master with the latest Nypr-UI.

**Pull request merged**
